development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  # username: postgres
  # password: 123456

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  # username: postgres
  # password: 123456
